### ISSUE TITLE
Collections: Support for two levels(支持二级分类)

### ISSUE THREAD

**Issue by nanzm** [oss-compass/compass-web#143]
在仓库中新增 `collections.yml` 用于定义二级分类结构。 yaml 结构如下：

```yaml
- ident: development-framework # 一级分类唯一标识符
  name: Development Framework # 英文一级分类名称
  name_cn: 开发框架 # 中文一级分类名称
  items: # 二级分类列表
    - css-framework  # collections/ 下 Collection YAML 文件中的 Ident 标识符
```

对应 Collections 页面导航的分类做二级折叠效果
