### ISSUE TITLE
Front End Dev: Collection YAML Design（分类页面后台数据调用）

### ISSUE THREAD

**Issue by eyehwan** [oss-compass/compass-web#66]
OSS Compass Collection 使用 Docusaurus Pages 进行开发，Meta 数据通过 YAML 存储于仓库中，直接通过前端进行渲染。使用`仓库地址`和主服务工程进行关联（传入仓库地址作为查询条件），具体实现要求如下：

> 仓库地址：https://github.com/oss-compass/Collection-Meta.git

仓库目录结构如下：

```bash
├── README.yml
├── collection // Colltction Meta 数据
│   ├── IaaS.yml
│   ├── Blockchain.yml
│   ├── Scripted Charts.yml
│   ├── Edge Computing Framework.yml
│   ├── SQL Database.yml
│   ├── Big Data.yml
│   └── Edge Computing.yml
└──  explore // Explore 页面配置项
```

YAML 结构如下：

```yaml

id: [Int]
name: Edge Computing
name_cn: 边缘计算
slug: /edge-computing
items:
  - gitee.com/example/repo
  - gitee.com/example/repo
  - github.com/example/repo
  - github.com/example/repo
  - ...
```

对应释义：

`name`: 分类名称
`name_cn`: 分类名称中文释义
`items`: 列表，内容为带域名但不带 SCHEMA 的仓库地址
